name: run the tests

on: [push]

jobs:
  test:
    name: run the existing tests
    runs-on: ubuntu-latest

    services:
      database:
        image: postgres:12-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          DATABASE_URL: postgres://postgres:password@localhost/postgres
